[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pay"
version = "0.1.0"

[project.optional-dependencies]
test = [
    "pytest >=7.1.3,<8.0.0"
]
