name: Running simple pytest example with dagger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r .devcontainer/requirements.txt

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Run dagger-pytest via just
        run: |
          just


